name: Release

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: oven-sh/setup-bun@v2

      - name: Install dependencies
        run: bun install

      - name: Zip extensions
        run: |
          bun zip
          bun zip:firefox

      - name: Check version change
        id: version
        run: |
          VERSION=$(jq -r .version package.json)
          echo "::set-output name=version::$VERSION"
          if git tag | grep -q "$VERSION"; then
            echo "Version $VERSION already exists."
            exit 0
          fi

      - name: Create GitHub Release
        uses: actions/create-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: v${{ steps.version.outputs.version }}
          release_name: v${{ steps.version.outputs.version }}
          draft: false
          prerelease: true

      - name: Upload Release Assets
        uses: softprops/action-gh-release@v1
        with:
          tag_name: v${{ steps.version.outputs.version }}
          files: |
            .output/**
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
