name: Release

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: oven-sh/setup-bun@v2

      - name: Install dependencies
        run: bun install

      - name: Zip extensions
        run: |
          bun zip
          bun zip:firefox

      - name: Check version change
        id: version
        run: |
          VERSION=$(jq -r .version package.json)
          echo "version=$VERSION" >> $GITHUB_ENV
          if git tag | grep -q "$VERSION"; then
            echo "Version $VERSION already exists."
            exit 0
          fi

      - name: Create GitHub Release
        id: create_release  # Добавляем id для использования в следующем шаге
        uses: actions/create-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: v${{ env.version }}
          release_name: v${{ env.version }}
          draft: false
          prerelease: true

      - name: Upload Release Assets
        if: steps.create_release.outputs.id != ''  # Условие для выполнения, только если релиз создан
        uses: softprops/action-gh-release@v1
        with:
          tag_name: v${{ env.version }}
          release_id: ${{ steps.create_release.outputs.id }}  # Используем ID релиза
          files: |
            .output/**
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
