name: Release

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: oven-sh/setup-bun@v2

      - name: Install dependencies
        run: bun install

      - name: Zip extensions
        run: |
          bun zip
          bun zip:firefox

      - name: Check version change
        id: version
        run: |
          VERSION=$(jq -r .version package.json)
          echo "version=$VERSION" >> $GITHUB_ENV
          if git tag | grep -q "$VERSION"; then
            echo "Version $VERSION already exists."
            exit 0
          fi

      - name: Check if release exists
        id: check_release
        run: |
          VERSION=$(jq -r .version package.json)
          if gh release view "v$VERSION"; then
            echo "Release v$VERSION already exists."
            echo "release_exists=true" >> $GITHUB_ENV
          else
            echo "release_exists=false" >> $GITHUB_ENV
          fi
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Create GitHub Release
        if: env.release_exists == 'false'
        id: create_release
        uses: actions/create-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: v${{ env.version }}
          release_name: v${{ env.version }}
          draft: false
          prerelease: true

      - name: Upload Release Assets
        if: env.release_exists == 'false'
        uses: softprops/action-gh-release@v1
        with:
          tag_name: v${{ env.version }}
          release_id: ${{ steps.create_release.outputs.id }}
          files: |
            .output/*.zip  # Загрузка только zip-файлов
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
